### ISSUE TITLE
Subplots option doesn't show multiple charts when in bar charts using bokeh as renderer

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/pixiedust#192] opened 2017-03-01 16:38 UTC

**Comment by DTAIEB** [comment] 2017-03-02 20:47
Fixed as part of #219

**Comment by jessmantaro** [comment] 2017-03-06 16:45
I still see this issue. Bokeh shows the "grouped" chart. I can show you.

**Comment by DTAIEB** [comment] 2017-03-07 04:14
Closing as duplicate of #233

**Closed** 2017-03-07 04:14 UTC
