### ISSUE TITLE
display() map chart: API keys should be retained

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#208] opened 2017-03-01 17:25 UTC
0.86 (not data set specific)

```
import pixiedust
df=pixiedust.sampleData(2)
display(df)
```

* Select `map` chart type 
* Enter an API key under _options_
* Switch to another chart type
* Select `map` chart type 

### Expected behavior

The API key is retained.

### Actual behavior

The API key needs to be re-entered again.

**Comment by DTAIEB** [comment] 2017-03-02 20:43
Can't reproduce anymore with the latest code. May have been fixed indirectly.

**Comment by ptitzler** [comment] 2017-03-04 00:40
No longer reproducable in 0.88. Tested google and mapbox API token.
:+1:

**Closed** 2017-03-07 18:13 UTC
Labels: bug
