### ISSUE TITLE
PixieDust Histogram Behaves Differently Now

### ISSUE THREAD

**Issue by dxkikuchi** [ibm-cds-labs/pixiedust#314] opened 2017-04-25 14:50 UTC
Using the same notebook, I am getting a radically different histogram than in prior releases of PixieDust.  The difference was identified in PixieDust 1.0.4.  I believe that this is due to the fact that the histogram is using SUM rather than COUNT.  Would be great to have the flexibility to chose with a pull down similar to bar chart options.

Here is a screen capture showing the difference.  Left image is before, right image is current with 1.0.4.
![screen shot 2017-04-25 at 10 48 50 am](https://cloud.githubusercontent.com/assets/12376383/25391739/e7960ed0-29a4-11e7-975a-0a8e33f1b1a4.jpg)

Also, the new "#rows to include" would be better with a larger default.  Or better, return to process all the rows.

Thank you.

**Comment by DTAIEB** [comment] 2017-04-25 14:52
This is probably a regression and needs to be fixed ASAP (1.0.5)

**Comment by vabarbosa** [comment] 2017-05-01 04:30
@dxkikuchi the histogram appears to be correct. PixieDust is not doing a SUM of the values before calling the histogram function. if you try to create the histogram (without PixeDust) you should see the similar result:

<img width="705" alt="screen shot 2017-05-01 at 12 29 23 am" src="https://cloud.githubusercontent.com/assets/13156555/25572085/52a85606-2e05-11e7-9c5e-4d400b06cb54.png">


i tried going back to PixieDust 1.0.3, 1.0.2, 1.0.1, and 1.0 and all produced the same result. which earlier version were you running before upgrading to 1.0.4?

what i can think of that may have created the discrepancy you saw is if the `# of Rows to Display` is not set to the total number of available rows. in which case, a sample of the total available rows is taken and used for the histogram. and depending on how small that sample is and which rows got selected the resulting histogram may be very different.

**Comment by dxkikuchi** [comment] 2017-05-01 05:20
@vabarbosa Thanks for your research and investigation.  I have attempted to increase the "# of Rows to Display" to 10,000 but the results still didn't resemble what I got previously.  I don't recall what version of PixieDust I used at the time.  I'm not sure how to interpret the results and I'm traveling this week.  I'd like to take a closer look at this when I can.  Thanks again.

**Comment by vabarbosa** [comment] 2017-05-01 08:15
@dxkikuchi  in the current chart your are seeing the histogram for all 1000 rows available (i.e., # rows is set to 1000 or more... changing to 10,000 makes no difference since nyvDF only has 1000 rows). in the earlier chart you are seeing the histogram of only 100 rows which means # rows was set to 100 at that time (or nyvDF only had 100 rows).

if you list the violations by count and compare it to the histograms:

<img width="399" alt="screen shot 2017-05-01 at 3 26 10 am" src="https://cloud.githubusercontent.com/assets/13156555/25574610/0110aea6-2e1e-11e7-8ddd-fd878a0f94e3.png">

you will notice that violations 2, 3, 4 total more than 900 which the recent histogram correctly shows. looking at the older histogram it is showing only 100 violations with violations 2, 3, and most of 4 not included. more specifically, it showing the first 100 violations (navDF is `order by Violations desc`).

with that said, the discrepancy is due to one of two reasons

- you had been running an early beta version of PixieDust because the older histogram was using the first **_n_** rows. this had since been changed (prior to version 1.0) to take a sample of **_n_** rows rather than just the first **_n_** rows

- you initially had nyvDF limited to only 100 rows but had since changed it to 1000

changing the your nyvDF query to limit to 100 gets your the original histogram:

<img width="839" alt="screen shot 2017-05-01 at 4 10 06 am" src="https://cloud.githubusercontent.com/assets/13156555/25575354/6980c3da-2e24-11e7-9f42-f190d0890050.png">

hopefully, this helps to clear up some of the confusion.

**Comment by vabarbosa** [comment] 2017-05-01 08:26
i am going to close this issue as this doesn't appear to be a regression or an issue as originally suspected.

however, as recommended i have increased the default value of # of Rows to Display (from 100 to 500).

regarding aggregation, there is no aggregation being done by PixieDust for histograms. any aggregation is handled by the renderer. therefore, it is advised to add an aggregation chart option.

feel free to re-open if there are any unresolved issues or any disagreements that should be discussed further.

**Closed by vabarbosa** 2017-05-01 08:26 UTC

**Comment by dxkikuchi** [comment] 2017-05-01 15:34
@vabarbosa Yes, please close this issue with my sincere thanks.
